name: shocksgo

channels:
    - astropy
    - conda-forge

dependencies:
    - python>=3.5
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - pybind11
    - celerite
    - scipy
#    - pip:

